title: "George Vengrovski"
description: ""
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
permalink: /:title/
# uncomment below if you want relative urls for github pages
# relative_permalinks: true